DROP TABLE IF EXISTS pf_magic_items;
CREATE TABLE pf_magic_items(
    id integer  NOT NULL PRIMARY KEY AUTO_INCREMENT
  , name varchar(46)
  , aura varchar(64)
  , cl varchar(6)
  , slot varchar(24)
  , price varchar(45)
  , weight varchar(42)
  , description text
  , requirements text
  , cost varchar(102)
  , `group` varchar(16)
  , source varchar(30)
  , al varchar(28)
  , `int` integer
  , wis varchar(17)
  , cha integer
  , ego varchar(29)
  , communication varchar(45)
  , senses varchar(58)
  , powers text
  , magic_items varchar(178)
  , `fulltext` text
  , destruction text
  , minor_artifact_flag bit
  , major_artifact_flag bit
  , abjuration bit
  , conjuration bit
  , divination bit
  , enchantment bit
  , evocation bit
  , necromancy bit
  , transmutation bit
  , aura_strength varchar(8)
  , weight_value varchar(5)
  , price_value integer
  , cost_value integer
  , languages varchar(44)
  , base_item varchar(101)
  , linktext varchar(87)
  , mythic bit
  , legendary_weapon bit
  , illusion bit
  , universal bit
  , created_at datetime
  , updated_at datetime
) engine=innodb default charset=utf8 collate=utf8_unicode_ci;