DROP TABLE IF EXISTS pf_monsters;
CREATE TABLE pf_monsters(
    id integer  NOT NULL PRIMARY KEY AUTO_INCREMENT
  , name varchar(33)
  , cr varchar(5)
  , xp integer
  , race varchar(27)
  , class varchar(26)
  , monster_source varchar(33)
  , alignment varchar(31)
  , size varchar(10)
  , type varchar(49)
  , subtype varchar(50)
  , ac varchar(93)
  , hp integer
  , hd varchar(28)
  , saves varchar(103)
  , fort varchar(32)
  , ref varchar(18)
  , will varchar(46)
  , speed varchar(66)
  , melee text
  , ranged varchar(93)
  , space varchar(14)
  , reach varchar(47)
  , ability_scores varchar(46)
  , feats text
  , skills text
  , racial_mods text
  , languages text
  , sq text
  , environment varchar(107)
  , organization text
  , treasure text
  , `group` varchar(23)
  , source varchar(30)
  , is_template bit
  , `fulltext` text
  , gear varchar(172)
  , other_gear varchar(118)
  , character_flag bit
  , companion_flag bit
  , fly bit
  , climb bit
  , burrow bit
  , swim bit
  , land bit
  , templates_applied varchar(22)
  , age_category varchar(5)
  , dont_use_racial_hd bit
  , variant_parent varchar(6)
  , class_archetypes varchar(14)
  , companion_familiar_link varchar(4)
  , alternate_name_form varchar(24)
  , unique_monster bit
  , mr integer
  , mythic bit
  , mt bit
  , created_at datetime
  , updated_at datetime
) engine=innodb default charset=utf8 collate=utf8_unicode_ci;